### ISSUE TITLE
Improve the README file

### ISSUE THREAD

**Issue by srivatsav1998** [srivatsav1998/slac#10]

**Comment by ZamaSharik** [comment]
I'd love to work on it.. But improvements in terms of what? Can you be more specific
Thanks.

**Comment by anandpotukuchi** [comment]
id what i could. Please check it out. @srivatsav1998

**Comment by srivatsav1998** [comment]
Thanks for your interest to work on this @Sidsharik but the issue is closed now.

**Comment by srivatsav1998** [comment]
Thanks, @anandpotukchi for your contribution. But the changes you have made are no longer applicable.
